### ISSUE TITLE
Reduce logging level from critical to info.

### ISSUE THREAD

**Issue by asford** [cjrh/aiorun#13]
Would you be open to reducing the logging level for some components of the `aiorun.run` function from `critical` to `info`? In particular, it would be great if the "default" mode of an asyncio application, in which the main function run via `aiorun.run(main())` cleanly exits via a call to `loop.stop()`, logged at the `info` level left the higher logging levels for (a) logging signal handlers and (b) logging if pending tasks are canceled.

I'd be happy to open a PR if this seems acceptable.

**Comment by cjrh** [comment]
Yep, this has come up before. By all means make a PR 👍

**Comment by cjrh** [comment]
Resolved in #17. I will try to make a release soon.
