### ISSUE TITLE
python3.7 has asyncio.run() function now

### ISSUE THREAD

**Issue by chenjiandongx** [cjrh/aiorun#16]
the latest python version 3.7 brings asyncio.run() function,it is a great feature

now we cloud use it easily, example

```python
import asyncio

async def main():
    await asyncio.sleep(1.0)
    print("hello cjrh!")

asyncio.run(main())
```

And your aiorun is aslso an awesome library.

**Comment by cjrh** [comment]
Thank you for your kind words :)

Yes `asyncio.run()` is a nice addition to the stdlib.  It also does task cancellation, like `aiorun`, but it doesn't add any of the signal handlers, nor does it shut down the executor.  I am considering refactoring `aiorun` to make use of `asyncio.run()`, but I just haven't had time to think about it in detail yet.

**Comment by MarSoft** [comment]
The thing I like the most in `aiorun` is `shutdown_waits_for` which is missing in `asyncio.run`.
