### ISSUE TITLE
Unhandled exception causes "Task exception was never retrieved"

### ISSUE THREAD

**Issue by iangoldby** [cjrh/aiorun#25]
An unhandled exception results in "Task exception was never retrieved".

Example:
```
import asyncio
from aiorun import run

async def main():
    # Put your application code here
    raise Exception('not consumed')

if __name__ == '__main__':
    run(main())
```
Result:
```
TTask exception was never retrieved
future: <Task finished coro=<run.<locals>.new_coro() done, defined at C:\Users\Ian\.conda\envs\enerlytics\lib\site-packages\aiorun.py:165> exception=Exception('not consumed',)>
Traceback (most recent call last):
  File "C:\Users\Ian\.conda\envs\enerlytics\lib\site-packages\aiorun.py", line 175, in new_coro
    await coro
  File "test.py", line 6, in main
    raise Exception('not consumed')
Exception: not consumed
```
... and the event loop continues running.

If `main()` exits with an unhandled exception then `aiorun` should gracefully stop the event loop and reraise the exception.

**Comment by iangoldby** [comment]
I've just discovered it's even worse in the shutdown phase. If a task catches exceptions and its exception handler itself causes an exception then that exception is completely swallowed.

Example:
```
import asyncio
from aiorun import run

async def main():
    queue = asyncio.Queue()
    try:
        msg = await queue.get()
    except asyncio.CancelledError:
        print('Cancelled!')
        some_error # exception from this is 'lost'
        print('Never reached')

print('Press Ctrl+C')
run(main())
```

**Comment by cjrh** [comment]
Thanks for making the report!  

> If main() exits with an unhandled exception then aiorun should gracefully stop the event loop and reraise the exception.

So, here's the thing.

When I first made `aiorun`, the design goal was to be a better replacement for `loop.run_forever()`.  Here is the documentation:

https://docs.python.org/3/library/asyncio-eventloop.html#running-and-stopping-the-loop

>  loop.run_forever()
>
>   Run the event loop until stop() is called.

As you've observed, there is no way to stop the event loop other than calling `loop.stop`.  Now the question is: should it work like this or not?  In your report, you argue that unhandled exceptions should stop the loop.  Maybe so. But "run until stop is called" is an equally valid API, although perhaps less desirable depending on your use-case.

After I first created `aiorun`, upstream added a new `asyncio.run()` function that behaved more like `loop.run_until_complete`, and indeed, you can see [in the source](https://github.com/python/cpython/blob/3.8/Lib/asyncio/runners.py) that it calls `loop.run_until_complete` internally. I think that's interesting. `asyncio.run()` should work as you describe, i.e., an unhandled exception stops the `asyncio.run()` call.  Do you have experience with this, and does that work out in practice?

I have a lot of experience with using `loop.run_forever` and this project, `aiorun`. The domain was long-lived microservices. It was kinda convenient that unhandled exceptions did not kill the service. We used centralised logging to alert on exceptions appearing the logs, and fixed them that way.

I am however open to the idea of stopping for unhandled exceptions. One easy way to add that now, without switching over to `loop.run_until_complete()`, might be to add a new parameter to `aiorun.run` which is a callable that will be used as a customer exception handler: https://docs.python.org/3/library/asyncio-eventloop.html#error-handling-api

For example the API might look like (hypothetically):

```
def my_exc_handler(loop, context):
    print('Unhandled exception:', context)
    loop.stop()

aiorun.run(..., exception_handler=my_exc_handler)
```

This should stop the loop (inside the handler) and therefore trigger the shutdown sequence in `aiorun`.  (And of course, makes `aiorun` a bit more configurable).

Would this resolve the issue for you?

**Comment by iangoldby** [comment]
I definitely like the idea of a user 'last resort' exception handler, called for any task that otherwise would result in "Task exception was never retrieved" - which I think is what you are proposing. Would the handler run in the context of the task that excepted, or outside the event loop completely? I would strongly prefer the latter because the former can easily be achieved with a try/except around the body of the task itself (or a decorator).

(I do think a much safer default is that any exception that is ultimately unhandled should stop the process. After all an unanticipated exception could leave the process in an unknown state with internal data corrupted in an unpredictable way. But I understand this would be a breaking change.)

**Comment by iangoldby** [comment]
Just to be clear about what 'outside the event loop' meant above, I'm thinking that an unhandled exception in a task should case loop.run_forever() to exit, at which point the exception handler is called if there is one. Execution then goes back to loop.run_forever() if the exception handler didn't stop the event loop.

**Comment by cjrh** [comment]
I've added an idea in #28 

Instead of providing a custom exception handler, I've instead gone for the bool option. It would like this:

```
import aiorun

async def main():
    1/0
     
try:   
    aiorun.run(main(), stop_on_unhandled_errors=True)
except ZeroDivisionError:
    print("An exception stopped the loop")
```

Do these semantics make sense to you?  

The "last resort" for maximum configurability is to provide one's own `loop` object to `aiorun.run()`, and this allows you to configure the loop instance however you want, including a custom exception handler.  That's why I didn't want to add a custom exc handler to the `aiorun.run()` api.  For most users, just getting it to stop on unhandled exceptions (and reraise the error) should be enough.

What do you think?

**Comment by cjrh** [comment]
I've gone ahead and merged my PR. If it turns out to be not quite right, we can revisit.

**Comment by iangoldby** [comment]
Cool. That sounds very good. Thank you!

**Comment by iangoldby** [comment]
Thanks also for the heads-up about `loop.set_exception_handler()`.
