### ISSUE TITLE
Push latest master to the pypi

### ISSUE THREAD

**Issue by hellysmile** [cjrh/aiorun#48]
@cjrh can You please push latest master which includes https://github.com/cjrh/aiorun/pull/44 and  https://github.com/cjrh/aiorun/pull/46 to the pypi?

thanks a lot!

**Comment by cjrh** [comment]
I will after I fix the test failures on master. Realistically I will only be able to look at it by the weekend, which is when I will do the packaging.

**Comment by cjrh** [comment]
Just one test failure, on ubuntu-py3.8: https://github.com/cjrh/aiorun/actions/runs/121331005

**Comment by hellysmile** [comment]
Seems just increase timeouts is fine https://github.com/hellysmile/aiorun/pull/1/checks?check_run_id=729818270 https://github.com/hellysmile/aiorun/pull/2

**Comment by cjrh** [comment]
Done https://pypi.org/project/aiorun/
