### ISSUE TITLE
Question: Running under aiorun or asyncio?

### ISSUE THREAD

**Issue by sphh** [cjrh/aiorun#59]
Is there a way to figure out inside a task, if the loop runs under `aiorun` or pure `asyncio`?

**Comment by cjrh** [comment]
In most cases there is no difference because the actual event loop is the one in the standard library. I reckon if you're in a situation where you need to know you should probably just use the standard library's `run()`: https://docs.python.org/3/library/asyncio-task.html#asyncio.run

This does nearly everything that aiorun does, except for the signal handlers and one or two other things.

**Comment by cjrh** [comment]
Ah I see.  I think your choice is fine.  If aiorun simply being available is enough to know whether that's what you're using, then you could also make a utility function like

```python
def using_aiorun() -> bool:
    try:
        import aiorun
    except ImporError:
        return False
    else:
        return True
```

But this will make things like tests more difficult if you want to test both with and without aiorun.  I think your method of using an argument is fine.  You could also instead set a global (or a singleton pattern, same difference) if you want to be able to easily tell from anywhere, without have to pass your argument all over the place.

**Comment by cjrh** [comment]
https://en.wikipedia.org/wiki/Singleton_pattern#Python_implementation

**Comment by sphh** [comment]
I had the same idea to try to import `aiorun` and if that fails, assuming that I run under pure `asyncio`. But there is the edge case, that you have it installed, but still run the program under `asyncio`, e.g. by not importing it in the first place, simulating that it is missing. (I know, I know, that's a messy way to check a program …)

Since I don't like global variables and the function initiating the closing program is only two classes deep, I pass an argument through to it. But I like your Singleton approach! I'll ponder to change to this.

**Comment by cjrh** [comment]
Can I close this issue?
