### ISSUE TITLE
aiorun 2020.12.1 does not seem to work together with aiohttp 3.7.4

### ISSUE THREAD

**Issue by pavka14** [cjrh/aiorun#61]
We have several microservices running with aiorun
After update we get the following:
aiorun==2020.12.1 and aiohttp==3.6.2 -> works as before
aiorun==2019.4.1 and aiohttp==3.7.4 -> works as before
aiorun==2020.12.1 and aiohttp==3.7.4 -> outgoing requests do not work.

Unfortunately, I cannot get any reason more specific than this:

Traceback (most recent call last):
  File "/home/pavka/Documents/console/slayer2/venv/lib64/python3.9/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib64/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8500)

In the above instance, it is trying to talk to a local docker container but the same happens when trying to connect to external services:

Traceback (most recent call last):
  File "/home/servicelayer/.local/lib/python3.7/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 954, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 941, in create_connection
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
    return await fut
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 494, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('172.17.11.3', 8500)

Some help will be highly appreciated...

**Comment by cjrh** [comment]
@pavka14 Thanks for the report. The manifestation of the problem seem to be connection-related.  aiorun doesn't do anything with connections, TCP, etc., so I am skeptical that aiorun is causing the problem here.  

Opportunities for exploration:
- Does the connection error occur if you use the stdlib `asyncio.run` function instead of aiorun?
- Do you have a self-contained example, e.g. Dockerfile or similar, that I can run to repro?  (realistically, without a repro it is very unlikely I will be able to help)
- Have you reported to aiohttp and what have they said?
- It is possible (but very unlikely) that aiohttp is somehow changing the event loop policy.  If you comment out https://github.com/cjrh/aiorun/blob/master/aiorun.py#L189 (i.e., remove the setting of the default policy in aiorun) do you still get the problem?

Good luck

**Comment by cjrh** [comment]
It looks like under certain conditions aiohttp might be setting an event loop policy (using Gunicorn, looks like): https://github.com/aio-libs/aiohttp/blob/09ac1cbb4c07b4b3e1872374808512c9bc52f2ab/aiohttp/worker.py#L219

If you're using Gunicorn and aiohttp is changing the event loop policy like this, that is probably incompatible with what aiorun is doing so I think I will remove the branch where aiorun sets the default event loop policy if `use_uvloop` was not supplied.

However, I still don't think this is likely to be the cause of your connection errors.

**Comment by pavka14** [comment]
Our code goes into the "else" of the condition there (use_uvloop is False); commenting out the next line did not help though.
We do not use gunicorn so might be something else in aiohttp, I'll try to follow the logic in worker.py
Thanks for the pointers.

**Comment by cjrh** [comment]
@pavka14 Did you resolve the issue?

**Comment by pavka14** [comment]
Thanks @cjrh - we shuffled our code a bit and we have no issue now. I am not sure if we "solved it" as such or just side-stepped it, but all works now.

**Comment by cjrh** [comment]
Great to hear 🎉
