### ISSUE TITLE
executor_workers, change to Optional[int]?

### ISSUE THREAD

**Issue by f0ff886f** [cjrh/aiorun#65]
Hi! Thank you very much for this library, its very elegant, and to the point.

I have a suggestion regarding the `executor_workers` argument to `run()`:

The `ThreadPoolExecutor` specifies the `max_workers=None` argument (same as `max_workers: Optional[int] = None`) because it auto-calculates the threadpool size to be `os.cpu_count() * 5` (so on my PC, `16 * 5 = 80`, a far cry from aiorun's default 10).

aiorun however specifies this arg as `executor_workers: int = 10` which means I'll get type errors passing `None` to take advantage of `ThreadPoolExecutor`'s default.

I could simply do this calculation myself, but it seems like it'd be useful for aiorun to mirror its default executor. What do you think?

**Comment by cjrh** [comment]
Good point - I'll change it.

**Comment by cjrh** [comment]
This change is live on pypi in 2021.8.1: https://pypi.org/project/aiorun/
