### ISSUE TITLE
`shutdown_waits_for` example doesn't work as intended

### ISSUE THREAD

**Issue by Fuzzwah** [cjrh/aiorun#71]
In the readme the following example is given:

```
import asyncio
from aiorun import run, shutdown_waits_for

async def corofn():
    await asyncio.sleep(60)
    print('done!')

async def main():
    try:
        await shutdown_waits_for(corofn())
    except asyncio.CancelledError
        print('oh noes!')

run(main())
```

With the explanation:

> If you hit CTRL-C before 60 seconds has passed, you will see oh noes! printed immediately, and then after 60 seconds (since start), done! is printed, and thereafter the program exits.

I'm finding that this isn't the case. The program never actually exits on its own. 

(Also there's a missing `:` on the end of the `asyncio.CancelledError`)

**Comment by cjrh** [comment]
Thank you for the report.  300 stars and you're the first to spot the missing colon 😄 

I'm going to change the example to this:

```python
import asyncio
from aiorun import run, shutdown_waits_for

async def corofn():
    for i in range(10):
        print(i)
        await asyncio.sleep(1)
    print('done!')

async def main():
    try:
        await shutdown_waits_for(corofn())
    except asyncio.CancelledError:
        print('oh noes!')

run(main())
```
This will make it clearer to see what is happening.  When I run it, and hit CTRL-C, I see this:

```bash
$ python testshield.py 
0
1
2
3
4
^CStopping the loop
oh noes!
5
6
7
8
9
done!
```

I'm going to add the above to the README.  Do you see something different?

I'm running on Linux (popos 22.04) and Python 3.10.4, and aiorun master branch.

**Comment by cjrh** [comment]
I fixed the README in d54ba3cc594aae2affc2f0465e98ca0f247377d6.

**Comment by cjrh** [comment]
Checking if I'm understanding the report correctly:

> I'm finding that this isn't the case. The program never actually exits on its own.

Do you mean "if I never hit CTRL-C, then the program never exits"?  Because if that is what is meant, then this is correct.  `aiorun.run()` will never exit on its own, it will run forever until something makes it stop.

**Comment by Fuzzwah** [comment]
Gotcha. Sorry, I misunderstood that part of the readme.

Is there a way I can "nicely" make a `aiorun.run()` process exit? While I'm testing my script using CTRL-C is excellent, but now that I'm looking to rig my python script up as a linux service I'm looking for a way to be able to trigger a halt in a nice way.

**Comment by cjrh** [comment]
Yep:

```python
import asyncio

async def main():
    try:
        <do your stuff here>
    finally:
        asyncio.get_running_loop().stop()
    
run(main())
```

By simple stopping the loop, the graceful-shutdown procedures inside aiorun will take over, cancel all pending tasks etc.

If this resolves it, pls feel free to close the issue 👍🏼
