### ISSUE TITLE
Mishmash of logging/printing

### ISSUE THREAD

**Issue by ldesgoui** [cjrh/aiorun#8]
Hello,

aiorun currently makes use of python's logging module, yet one call to print remains, would it be possible to have it removed or logged in the next version?
https://github.com/cjrh/aiorun/blob/master/aiorun.py#L200

Thanks very much.

**Comment by cjrh** [comment]
Oops yeah that's an error on my part. Will fix it up tomorrow morning. Thanks for taking the time to report it!
