### ISSUE TITLE
loop.create_task without saving a reference to the result

### ISSUE THREAD

**Issue by kwist-sgr** [cjrh/aiorun#87]
Hi! Thank you for your library :smiley: 

I have a question about [this line of code](https://github.com/cjrh/aiorun/blob/master/aiorun.py#L221):
```python
loop.create_task(new_coro())
```
I am confused that the link to the result is not saved here.
Because there is a warning about this [in the documentation](https://docs.python.org/3/library/asyncio-task.html#creating-tasks).

Thank you in advance for your response.

**Comment by cjrh** [comment]
Yes it's odd isn't it?  I already noticed this quite a while ago. Check this out:

```python
import gc
import asyncio

async def blah():
    for i in range(20):
        print(i)
        await asyncio.sleep(1)

async def main():
    loop = asyncio.get_running_loop()
    loop.create_task(blah())
    gc.collect()

    await asyncio.sleep(20)
    print('main done')

if __name__ == '__main__':
    asyncio.run(main())
```

Even immediately calling `gc.collect()` doesn't make the referenceless task disappear.  I don't know why, but if you find out I would love to know :)

**Comment by cjrh** [comment]
Ah interesting.

I should probably make the change to assign the result to something anyway, because you never know if a future version of python becomes more aggressive to remove garbage earlier. It just seems silly to assign to a var that isn't used.

**Comment by kwist-sgr** [comment]
> It just seems silly to assign to a var that isn't used.

Yeah. 

Maybe, you can use a `dummy` variable here:
```python
_ = loop.create_task(new_coro())
```

**Comment by cjrh** [comment]
Yes ofc, but I hate needing to do that 😄

**Comment by cjrh** [comment]
Also, it's plausible in the general case that `_` might get used for something else in the same scope. Maybe not this project, but as a general solution. So `_` on it's own is probably not a good idea. Perhaps just `background_tasks` like the docs suggested.

**Comment by kwist-sgr** [comment]
Yes, this looks like the best solution.

P.S. I was worried about deleting the task after it's done, but it turns out there is already a solution based on `add_done_callback` in the documentation :smile: .

**Comment by kwist-sgr** [comment]
Small example based on [Asyncio Disappearing Task Bug](https://superfastpython.com/asyncio-disappearing-task-bug/#:~:text=You%20can%20have%20running%20background,and%20how%20to%20avoid%20it)

```python
# demo.py
import asyncio
import gc


async def bla():
    loop = asyncio.get_running_loop()
    future = loop.create_future()
    await future


async def main():
    asyncio.create_task(bla())

    for i in range(11):
        print('[gc collect]', i)
        gc.collect()
        await asyncio.sleep(1)
    print('main done')


if __name__ == '__main__':
    asyncio.run(main())
```

```shell
$ python -m demo 
[gc collect] 0
[gc collect] 1
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<bla() running at /home/user/demo.py:8> wait_for=<Future pending cb=[Task.task_wakeup()]>>
[gc collect] 2
...
[gc collect] 10
main done
```

**Comment by sersorrel** [comment]
fwiw, this same pattern is repeated in a couple of other places:

https://github.com/cjrh/aiorun/blob/aec5682fee41c709b34cf85c416c14f325f4b449/aiorun.py#L221

https://github.com/cjrh/aiorun/blob/aec5682fee41c709b34cf85c416c14f325f4b449/aiorun.py#L243

I have no idea if there is even a theoretical scenario where this could cause a problem, though.
